# Generated by Django 4.1.5 on 2023-01-14 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_document_user_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='message',
        ),
    ]
